[pytest]
pythonpath =
    "."
    "helpers"

addopts = 
    ; --cov=processors
    ; --cov=helpers
    ; --cov-report=term-missing
    ; ; --cov-fail-under=92
    ; --cov-branch
    ; --cov-report=xml
    ; --junitxml=unittest.junit.xml
    ; -o junit_family=legacy
